Allow importing with exports-aware Typescript
Trying to import the library could run into the following issue:

 error TS7016: Could not find a declaration file for module '@signalapp/sqlcipher'. '.../node_modules/@signalapp/sqlcipher/dist/index.mjs' implicitly has an 'any' type.
  There are types at '.../node_modules/@signalapp/sqlcipher/dist/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@signalapp/sqlcipher' library may need to update its package.json or typings.

  The issue comes from mismatch where index.mjs does not automatically
  map to index.d.ts (it would have to be index.d.mts).

  The solution is to add types to export. The other "type" key could
  be removed but is left in for now for compatibility with old tsc
  versions.